[nodes]
    [nodes.1]
    pk = "A"
    slices = {t = 3, validators = ['B', 'C', 'D']}

    [nodes.2]
    pk = "B"
    slices = {t = 3, validators = ['A', 'C', 'D']}

    [nodes.3]
    pk = "C"
    slices = {t = 3, validators = ['B', 'A', 'D']}

    [nodes.4]
    pk = "D"
    slices = {t = 3, validators = ['B', 'C', 'A']}

    # [nodes.5]
    # pk = "E"
    # slices = {t = 3, validators = ['B', 'C', 'A', 'F']}

    # [nodes.6]
    # pk = "F"
    # slices = {t = 3, validators = ['B', 'C', 'A', 'E']}